config/routes.rb
Rails.application.routes.draw do

  resources :portals
  get 'handshake' => 'handshake#index'
  match 'rpc/playerUndecorated/:action', to: 'player_undecorated#:action', via: [:get, :post]
  match 'rpc/gameplay/:action', to: 'gameplay#:action', via: [:get, :post]
end

app/models/portal.rb
require 'dtos/portal_dto'

class Portal < ActiveRecord::Base
  def self.findNearestPortals(playerLatitude, playerLongitude)
    # Distance algorithm: http://andrew.hedges.name/experiments/haversine

    #   a = (sin((lat2 - lat1)/2))^2 + cos(lat1) * cos(lat2) * (sin((lon2 - lon1)/2))^2
    #   c = 2 * atan2( sqrt(a), sqrt(1-a) )
    #   d = R * c (where R is the radius of the Earth)

    #   lat1 = 38.898556
    #   lon1 = -77.037852
    #   lat2 = 38.897147
    #   long2 = -77.043934
    #   d = 0.341 miles
    #   d = 0.549 kilometers

    earthRadiusMiles = '3961'
    degreesToRadians = '57.2958'
    portalRange = '0.1'

    distanceSubquery = '((sin(((%{playerLatitude} / %{degreesToRadians}) - (latitude / 1E6 / %{degreesToRadians})) / 2))^2 + cos(latitude / 1E6 / %{degreesToRadians}) * cos((%{playerLatitude} / %{degreesToRadians})) * (sin(((%{playerLongitude} / %{degreesToRadians}) - (longitude / 1E6 / %{degreesToRadians})) / 2))^2))'
    distanceSubquery = '(2 * atan2(sqrt(%{distanceSubquery}, sqrt(1 - %{distanceSubquery})) * %{earthRadiusMiles}' % {
        :distanceSubquery => distanceSubquery,
        :earthRadiusMiles => earthRadiusMiles
    }
    distanceSubquery = distanceSubquery % {
        :degreesToRadians => degreesToRadians,
        :playerLatitude => playerLatitude,
        :playerLongitude => playerLongitude
    }
    return Portal.select(distanceSubquery + ' as distance, *').order('distance ASC').where(distanceSubquery + ' <= ' + portalRange)
  end

  def self.fromPortal(portal)
    return Portal.fromPortalDTO(PortalDTO.new(portal))
  end

  def self.fromPortalDTO(portal)
    return [
        # guid
        portal.id,
        # timestamp
        1412819501000,
        {
            'locationE6' => {
                'latE6' => portal.latitude * 1E6,
                'lngE6' => portal.longitude * 1E6
            },
            'resourceWithLevels' => {
                'resourceType' => nil
            },
            'modResource' => {
                'resourceType' => nil
            },
            'controllingTeam' => {
                'team' => ''
            },
            'imageByUrl' => {
                'imageUrl' => portal.imageUrl
            },
            'portalV2' => {
                'descriptiveText' => {
                    'TITLE' => portal.name,
                    'ADDRESS' => nil # TODO: Not tested, might throw an error.
                },
                'linkedModArray' => [
                    nil,
                    nil,
                    nil,
                    nil
                ]
            },
            'captured' => {
                'capturingPlayerId' => '40e2a146907e493fa1902705c46eba78',
                'nickname' => 'uncaptured'
            },
            'resonatorArray' => {
                'resonators' => [
                    nil,
                    nil,
                    nil,
                    nil,
                    nil,
                    nil,
                    nil,
                    nil
                ]
            }
        }
    ]
  end

  def self.fromGooglePlace(spot)
    portal = Portal.find_by_googlePlaceId(spot.place_id)

    if !portal
      portal = Portal.new
      portal.name = spot.name.truncate(50)
      portal.latitude = spot.lat * 1E6
      portal.longitude = spot.lng * 1E6
      portal.imageUrl = spot.icon
      portal.googlePlaceId = spot.place_id
      portal.save
    end

    return Portal.fromPortal(portal)
  end
end

app/controllers/portals_controller.rb
class PortalsController < ApplicationController
  before_action :set_portal, only: [:show, :edit, :update, :destroy]

  # GET /portals
  # GET /portals.json
  def index
    @portals = Portal.all
  end

  # GET /portals/1
  # GET /portals/1.json
  def show
  end

  # GET /portals/new
  def new
    @portal = Portal.new()
  end

  # GET /portals/1/edit
  def edit
  end

  # POST /portals
  # POST /portals.json
  def create
    @portal = Portal.new(portal_params)

    respond_to do |format|
      if @portal.save
        format.html { redirect_to @portal, notice: 'Portal was successfully created.' }
        format.json { render :show, status: :created, location: @portal }
      else
        format.html { render :new }
        format.json { render json: @portal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portals/1
  # PATCH/PUT /portals/1.json
  def update
    respond_to do |format|
      if @portal.update(portal_params)
        format.html { redirect_to @portal, notice: 'Portal was successfully updated.' }
        format.json { render :show, status: :ok, location: @portal }
      else
        format.html { render :edit }
        format.json { render json: @portal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portals/1
  # DELETE /portals/1.json
  def destroy
    @portal.destroy
    respond_to do |format|
      format.html { redirect_to portals_url, notice: 'Portal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portal
      @portal = Portal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portal_params
      params.require(:portal).permit(:name, :imageUrl, :latitude, :longitude, :googlePlaceId)
    end
end

app/helpers/portals_helper.rb
module PortalsHelper
end

app/views/portals/_form.html.erb
<%= form_for(@portal) do |f| %>
    <% if @portal.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@portal.errors.count, "error") %> prohibited this portal from being saved:</h2>
          <ul>
            <% @portal.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div>
      <%= f.label :imageUrl %><br>
      <%= f.text_field :imageUrl %>
    </div>
    <div>
      <%= f.label :latitude %><br>
      <%= f.text_field :latitude %>
    </div>
    <div>
      <%= f.label :longitude %><br>
      <%= f.text_field :longitude %>
    </div>
    <div>
      <%= f.label :googlePlaceId %><br>
      <%= f.text_field :googlePlaceId %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/portals/edit.html.erb
<h1>Editing portal</h1>

<%= render 'form' %>

<%= link_to 'Show', @portal %> |
<%= link_to 'Back', portals_path %>

app/views/portals/index.html.erb
<h1>Manage Portals</h1>
<table>
  <thead>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Google Place Id</th>
    <th colspan="3">Options</th>
  </tr>
  </thead>
  <tbody>
  <% @portals.each do |portal| %>
      <tr>
        <td><%= portal.id %></td>
        <td><%= link_to portal.name, portal.imageUrl %></td>
        <td><%= portal.latitude %></td>
        <td><%= portal.longitude %></td>
        <td><%= portal.googlePlaceId %></td>
        <td><%= link_to 'Show', portal %></td>
        <td><%= link_to 'Edit', edit_portal_path(portal) %></td>
        <td><%= link_to 'Destroy', portal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Portal', new_portal_path %>

app/views/portals/new.html.erb
<h1>New Portal</h1>

<%= render 'form' %>

<%= link_to 'Back', portals_path %>

app/views/portals/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_portal_path(@portal) %> |
<%= link_to 'Back', portals_path %>